# Generated by Django 3.2.5 on 2021-09-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='websiteurl',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
