# Generated by Django 3.2.5 on 2021-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteurl',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
