# Generated by Django 3.1.8 on 2021-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_filesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteurl',
            name='status_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='filesupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
